[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
ggez = "0.9.3"
image = "0.24.6"
rand = "0.8.5"
serde = "1.0.182"
serde_json = "1.0.104"
